name: Build Windows EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      # --- THIS IS THE NEW STEP ---
      # This command downloads all the necessary libraries defined in go.mod
      - name: Download and Verify Dependencies
        run: go mod tidy

      # We are going back to the local path, which is correct after running go mod tidy
      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -v -o webhookd.exe ./cmd/webhookd

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: webhookd-windows-binary
          path: webhookd.exe
