name: Build Windows EXE

# This makes the workflow run automatically when you push a change,
# and also allows you to run it manually from the Actions tab.
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Build for Windows
        # This command forces Go to build for Windows and names the output webhookd.exe
        run: GOOS=windows GOARCH=amd64 go build -o webhookd.exe github.com/ncarlier/webhookd/cmd/webhookd

      - name: Upload Windows EXE
        # This action takes the file we just created and makes it a downloadable artifact
        uses: actions/upload-artifact@v4
        with:
          name: webhookd-windows-binary
          path: webhookd.exe
